Repository monarchmoney/mint-export-extension, pull requests merged in 2023-11, with the labels that each got.

#9 Skip accounts that error
  src/components/popup/DownloadBalances.tsx
  src/pages/background/index.ts
  src/shared/lib/__tests__/promises.test.ts
  src/shared/lib/accounts.ts
  src/shared/lib/promises.ts
Labels: bug

#10 Add Sentry by default for error tracking
  package.json
  pnpm-lock.yaml
  src/pages/background/index.ts
  src/pages/popup/Popup.tsx
  vite.config.ts
Labels: enhancement

#11 Tweaks to README - Add link to download latest release
  .github/workflows/release-stable.yml
  README.md
Labels: documentation
